### ISSUE TITLE
an error in code

### ISSUE THREAD

**Issue by KaizhengLiu** [roever/BSP#1]
in the function `bsp::evaluatePivot`
`         sign(distance(plane, vertex_traits<vertex_type>::getPosition(get(vertices_, i  )))),
          sign(distance(plane, vertex_traits<vertex_type>::getPosition(get(vertices_, i+1)))),
          sign(distance(plane, vertex_traits<vertex_type>::getPosition(get(vertices_, i+2))))`
should be 
`        sign(distance(plane, vertex_traits<vertex_type>::getPosition(get(vertices_,  get(indices,     i))))),
          sign(distance(plane, vertex_traits<vertex_type>::getPosition(get(vertices_, get(indices, i+1))))),
          sign(distance(plane, vertex_traits<vertex_type>::getPosition(get(vertices_, get(indices, i+2)))))`

**Comment by roever** [comment]
thanks, fixed, but by using the helper function in the class.
